language: python
matrix:
  include:
  - os: linux
    cache: apt
    dist: xenial
    python: '3.6'
    env: DEPLOY="true"
addons:
  apt:
    packages:
    - python-usb
    - python-setuptools
    - dfu-util
    - gcc-arm-none-eabi
    - libnewlib-arm-none-eabi
    - libstdc++-arm-none-eabi-newlib
    - liblzma5
  homebrew:
    taps: armmbed/formulae
    packages:
    - arm-none-eabi-gcc
    - dfu-util
before_install:
- pip install PyYAML
before_script:
- export CFLAGS="-Wall -Wextra"
- export PYTHONPATH="/home/travis/.local/lib/python3.6/site-packages/:/home/travis/.local/lib/python2.7/site-packages/"
script:
- pushd libgreat/host/
- python setup.py build
- sudo $(which python) setup.py install
- popd
- pushd host/
- python setup.py build
- sudo $(which python) setup.py install
- popd
- make firmware
before_deploy:
- openssl aes-256-cbc -K $encrypted_3584182e1d21_key -iv $encrypted_3584182e1d21_iv
  -in id_deploy.enc -out id_deploy -d
- mkdir bin
- sudo $(which python) -m pip install git-archive-all
- eval "$(ssh-agent -s)"
- chmod 600 id_deploy
- ssh-add id_deploy
- echo $KNOWN_HOSTS_ENTRIES >> $HOME/.ssh/known_hosts
deploy:
  provider: script
  script: make deploy_nightly VERSION_SUFFIX="auto-nightly" USE_NIGHTLY_VERSIONING=1
  on:
    branch: master
    condition: $DEPLOY = "true"
